### ISSUE TITLE
Crash on invalid input when conscripting soldiers

### ISSUE THREAD

**Issue by LeonardMH** [brumafriend/BrumaGame#3]
Found your game on reddit! On being prompted with: 

```
How many people would you like to conscript?
(1000 people conscripted = tension increase of 10%)
```

I hit enter without typing anything and the game crashed with:

```
Traceback (most recent call last):
  File "GameCode.py", line 504, in <module>
    start()
  File "GameCode.py", line 208, in start
    con = int(input(""))
ValueError: invalid literal for int() with base 10: ''
```

There are two improvements I'd make here... (1) make it clear that you expect an integer to be entered on this command, I wasn't sure what to do. (2) sanitize the user input by catching ValueError and assigning con = 0 if exception is raised.

**Comment by brumafriend** [comment]
Should be fixed now.
